---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "middleware"
  namespace: "abuse-api-dev"
  labels:
    app: "middleware"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: "middleware"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "middleware"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/dcumiddleware:dev"
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: dev
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-middleware
                key: password
          - name: API_TOKEN
            valueFrom:
              secretKeyRef:
                name: api-token
                key: token
          - name: ABUSE_API_URL
            value: http://api.abuse-api-dev.svc.cluster.local:5000/v1/abuse/tickets
          - name: SERVICE_URL
            value: http://cmap-service.abuse-api-dev.svc.cluster.local:5000
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-middleware
                key: password
          - name: LOG_LEVEL
            value: DEBUG
          - name: CMAP_CERT
            value: /cmap_certs/tls.crt
          - name: CMAP_KEY
            value: /cmap_certs/tls.key
          volumeMounts:
          - name: tls-cmap-files
            mountPath: /cmap_certs
            readOnly: true
      volumes:
        - name: tls-cmap-files
          secret:
            secretName: tls-cmap
