apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-dev
images:
- digest: sha256:ea34a4b497e6e0c38a22cedc527fa89ad438102df3c5978fe86eecb1624ba0e1
  name: docker-dcu-local.artifactory.secureserver.net/dcumiddleware

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: LOG_LEVEL
        value: DEBUG
  target:
    kind: Deployment
    name: middleware
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ELASTIC_APM_ENVIRONMENT
        value: dev
  target:
    kind: Deployment
    name: middleware
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ABUSE_API_URL
        value: https://abuse.api.int.dev-godaddy.com/v1/abuse/tickets
  target:
    kind: Deployment
    name: middleware
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: SERVICE_URL
        value: http://cmap-service.abuse-api-dev.svc.cluster.local:5000
  target:
    kind: Deployment
    name: middleware
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: sysenv
        value: dev
  target:
    kind: Deployment
    name: middleware
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: SHOPPER_API_URL
        value: https://shopper.api.int.dev-godaddy.com
  target:
    kind: Deployment
    name: middleware
