apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-dev
images:
- digest: sha256:4e292379863f849db653172771a18fd98f11c82cbe01ac337f7b69293dadeb62
  name: docker-dcu-local.artifactory.secureserver.net/dcumiddleware

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: LOG_LEVEL
        value: DEBUG
  target:
    kind: Deployment
    name: middleware
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ELASTIC_APM_ENVIRONMENT
        value: dev
  target:
    kind: Deployment
    name: middleware
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ABUSE_API_URL
        value: http://api.abuse-api-dev.svc.cluster.local:5000/v1/abuse/tickets
  target:
    kind: Deployment
    name: middleware
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: SERVICE_URL
        value: http://cmap-service.abuse-api-dev.svc.cluster.local:5000
  target:
    kind: Deployment
    name: middleware
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: sysenv
        value: dev
  target:
    kind: Deployment
    name: middleware
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: SHOPPER_API_URL
        value: https://shopper.api.int.dev-godaddy.com
  target:
    kind: Deployment
    name: middleware
