services:
  dcumiddleware:
    image: gdartifactory1.jfrog.io/docker-dcu-local/dcumiddleware:dev
    environment:
      ABUSE_API_URL: ${ABUSE_API_URL}
      BROKER_URL: ${BROKER_URL}
      QUEUE_TYPE: 'quorum'
      DB_PASS: ${DB_PASS}
      CMAP_CLIENT_CERT: '/tmp/certs/cmapservice.client.cset.int.dev-gdcorp.tools.crt'
      CMAP_CLIENT_KEY: '/tmp/certs/cmapservice.client.cset.int.dev-gdcorp.tools.key'
      DISABLESSL: 'True'
      LOG_LEVEL: ${LOG_LEVEL}
      METRICS_ENABLED: 'yes'
      SERVICE_URL: ${SERVICE_URL}
      sysenv: ${sysenv}
      SSO_USER: ${SSO_USER}
      SSO_PASSWORD: ${SSO_PASSWORD}
    volumes:
      - /PATH_TO_YOUR_CERTS_DIRECTORY/:/tmp/certs/
    links:
      - rabbitmq:rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672