---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "middleware"
  namespace: "abuse-api-prod"
  labels:
    app: "middleware"
spec:
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: "middleware"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "middleware"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/dcumiddleware:REPLACE_WITH_GIT_COMMIT"
          resources:
            requests:
              memory: "300Mi"
            limits:
              memory: "1024Mi"
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: prod
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-middleware
                key: password
          - name: SERVICE_URL
            value: http://cmap-service.abuse-api-prod.svc.cluster.local:5000
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-middleware
                key: password
