---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "middleware"
  namespace: "abuse-api-ote"
  labels:
    app: "middleware"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "middleware"
  template:
    metadata:
      labels:
        app: "middleware"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        - name: pushgateway
          image: prom/pushgateway:v1.4.0
        - name: "middleware"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/dcumiddleware:ote"
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: ote
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-shared-creds
                key: password
          - name: SSO_USER
            valueFrom:
              secretKeyRef:
                name: abuse-api-user
                key: username
          - name: SSO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: abuse-api-user
                key: password
          - name: ABUSE_API_URL
            value: http://api.abuse-api-ote.svc.cluster.local:5000/v1/abuse/tickets
          - name: SERVICE_URL
            value: http://cmap-service.abuse-api-ote.svc.cluster.local:5000
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-v2
                key: password
          - name: LOG_LEVEL
            value: DEBUG
          - name: CMAP_CERT
            value: /cmap_certs/tls.crt
          - name: CMAP_KEY
            value: /cmap_certs/tls.key
          - name: METRICS_ENABLED
            value: 'yes'
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: secret
          volumeMounts:
          - name: tls-cmap-files
            mountPath: /cmap_certs
            readOnly: true
      volumes:
        - name: tls-cmap-files
          secret:
            secretName: tls-cmap
