---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "middleware"
  namespace: "abuse-api-ote"
  labels:
    app: "middleware"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "middleware"
    spec:
      imagePullSecrets:
        -
          name: "k8s-artifactory-creds"
      containers:
        -
          name: "middleware"
          imagePullPolicy: "Always"
          image: "artifactory.secureserver.net:10014/docker-dcu-local/dcumiddleware:ote-k8s"
          env:
          - name: sysenv
            value: ote
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-middleware
                key: password
          - name: SERVICE_URL
            value: https://cmapservice.int.ote-godaddy.com
          - name: KEYFILE
            value: /keyfiles/key.txt
          - name: AUTHPASS
            valueFrom:
              secretKeyRef:
                name: dcu-proxy-auth
                key: password
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                name: db-middleware
                key: password
          # redis used for a CELERY backend
          - name: REDIS
            value: middleware-redis.abuse-api-ote.svc.cluster.local
          - name: API
            value: api.abuse-api-ote.svc.cluster.local
          - name: SELENIUM_URL
            value: http://selenium-server.abuse-api-ote.svc.cluster.local:4444/wd/hub
          volumeMounts:
          - name: encryption-keys
            mountPath: /keyfiles
            readOnly: true

      volumes:
        - name: encryption-keys
          secret:
            secretName: encryption-key-files

