---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "middleware"
  namespace: "abuse-api-ote"
  labels:
    app: "middleware"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "middleware"
    spec:
      imagePullSecrets:
        -
          name: "k8s-artifactory-creds"
      containers:
        -
          name: "middleware"
          imagePullPolicy: "Always"
          image: "artifactory.secureserver.net:10014/docker-dcu-local/dcumiddleware:ote"
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: ote
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-middleware
                key: password
          - name: SERVICE_URL
            value: http://cmap-service.abuse-api-ote.svc.cluster.local:5000
          - name: KEYFILE
            value: /keyfiles/key.txt
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                name: db-middleware
                key: password
          volumeMounts:
          - name: encryption-keys
            mountPath: /keyfiles
            readOnly: true

      volumes:
        - name: encryption-keys
          secret:
            secretName: encryption-key-files

