---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "selenium-server"
  namespace: "abuse-api-ote"
  labels:
    app: "selenium-server"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "selenium-server"
    spec:
      imagePullSecrets:
        -
          name: "k8s-artifactory-creds"

      containers:
        -
          name: "selenium-server"
          imagePullPolicy: "Always"
          image: "selenium/standalone-chrome"
          ports:
            -
              containerPort: 4444
              protocol: "TCP"
