---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "middleware"
  labels:
    app: "middleware"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "middleware"
  template:
    metadata:
      labels:
        app: "middleware"
    spec:
      imagePullSecrets:
        - name: "artifactory-saas-creds"
      containers:
        - name: "middleware"
          imagePullPolicy: "Always"
          image: gdartifactory1.jfrog.io/docker-dcu-local/dcumiddleware
          livenessProbe:
            exec:
              command:
                - '/app/health.sh'
            periodSeconds: 20
            timeoutSeconds: 10
          env:
          - name: MULTIPLE_BROKERS
            valueFrom:
              secretKeyRef:
                name: amqp-shared-creds
                key: multiple_brokers_grandma
          - name: SSO_USER
            valueFrom:
              secretKeyRef:
                name: abuse-api-user
                key: username
          - name: SSO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: abuse-api-user
                key: password
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-v2
                key: password
          - name: CMAP_CLIENT_CERT
            value: /cmap_client_certs/tls.crt
          - name: CMAP_CLIENT_KEY
            value: /cmap_client_certs/tls.key
          - name: SHOPPER_API_CERT_PATH
            value: /cmap_client_certs/tls.crt
          - name: SHOPPER_API_KEY_PATH
            value: /cmap_client_certs/tls.key
          - name: METRICS_ENABLED
            value: 'yes'
          - name: KELVIN_DB_URL
            valueFrom:
              secretKeyRef:
                name: kelvin-mongourl
                key: mongoURL
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: secret
          - name: MONGO_CLIENT_CERT
            value: /mongo_common_certs/mongo_client.pem
          volumeMounts:
          - name: tls-middleware-client-cert
            mountPath: /cmap_client_certs
            readOnly: true
          - name: tls-mongo-common-cert-files
            mountPath: /mongo_common_certs
            readOnly: true
      volumes:
        - name: tls-middleware-client-cert
          secret:
            secretName: tls-middleware-client-cert
        - name: tls-mongo-common-cert-files
          secret:
            secretName: tls-mongo-common-cert-files